### ISSUE TITLE
Don't zip the files if it's just a single file

### ISSUE THREAD

**Issue by electronicwhisper** [PavelLaptev/tinify-Image-compressor-figma#1]
Great plugin!

Would you be open to a change where if there was only a single file being exported, it would not zip the single file?

I think code-wise it would just be here:
https://github.com/PavelLaptev/tinify-Image-compressor-figma/blob/30ad112c157f4569c5d86dda4cedc9886157e4d2/src/app/utils/zipAndSave.ts#L16-L18

You could have:
```
if (files.length === 0) {
  saveAs(file, file.name, {binary: true});
  return;
}
```

Haven't tried/tested that but just pattern matching from what I see...

**Comment by PavelLaptev** [comment]
@electronicwhisper Agreed :-) Will do it

**Comment by PavelLaptev** [comment]
@electronicwhisper done 🙂
